---
# Paso 1: Mostrar información del servidor
- name: Mostrar información del servidor
  debug:
    msg:
      - "=== Configurando servidor {{ inventory_hostname }} ==="
      - "IP: {{ ansible_host }}"
      - "Sistema: {{ ansible_distribution }} {{ ansible_distribution_version }}"

# Paso 2: Actualizar la caché de paquetes del sistema
- name: Actualizar cache de paquetes
  ansible.builtin.apt:
    name: '*'
    state: latest
  when: ansible_os_family == "Debian"

- name: Actualizar caché de apt
  ansible.builtin.apt:
    update_cache: yes

# Paso 3: Instalar y configurar Apache2
- name: Instalar Apache2
  ansible.builtin.apt:
    name: apache2
    state: latest

- name: Iniciar el servicio Apache2
  ansible.builtin.service:
    name: apache2
    state: started

- name: Eliminar el archivo index.html por defecto de Apache
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent
